services:
  schluend-website:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./.express_cms
        target: /usr/src/app/.express_cms
    ports:
      - "3009:3009"
